# Generated by Django 4.1.6 on 2024-11-11 06:35

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_score',
            new_name='Product_score',
        ),
        migrations.AlterModelOptions(
            name='product_score',
            options={'verbose_name': '商品评分', 'verbose_name_plural': '商品评分'},
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('c31841ff-a713-4623-8042-3cac5111c939'), max_length=100, verbose_name='交易ID'),
        ),
    ]
