# Generated by Django 4.1.6 on 2024-11-11 07:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_job_score_product_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('6b22a42f-045b-4e40-bd19-d466de66d254'), max_length=100, verbose_name='交易ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
