# Generated by Django 4.1.6 on 2024-11-11 07:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_order_transaction_id_alter_product_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('539a9d30-ec4f-45f3-826c-7568f56fced3'), max_length=100, verbose_name='交易ID'),
        ),
    ]
