# Generated by Django 4.1.6 on 2024-11-12 02:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('e6033f77-088c-42fa-ad5d-7bca96758b75'), max_length=100, verbose_name='交易ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='product_score',
            name='score',
            field=models.IntegerField(default=0, null=True, verbose_name='热度'),
        ),
    ]
