# Generated by Django 3.0 on 2025-01-26 02:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20250126_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('3801c856-603d-488b-be1c-b2327af90365'), max_length=100, verbose_name='交易ID'),
        ),
    ]
