# Generated by Django 3.0 on 2025-01-26 02:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20250126_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('4a159339-f101-4ee5-b798-675910759526'), max_length=100, verbose_name='交易ID'),
        ),
    ]
