# Generated by Django 3.0 on 2025-01-26 02:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20250126_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('a9795883-6f31-4ff1-8cc3-db37b486a43c'), max_length=100, verbose_name='交易ID'),
        ),
    ]
